before_install:
  - gem update --system
language: ruby
rvm: 
  - 1.9.2
env:
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.1
  - PUPPET_VERSION=3.5.1
  - PUPPET_VERSION=3.6.2
  - PUPPET_VERSION=3.7.3